/**
 *MarvelComicsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 07/18/2016
 */

'use strict';
angular.module('MarvelComicsLib',[]).factory('Configuration', function() {
    return {
        //The base Uri for API calls
        BASEURI : "http://gateway.marvel.com",

        referer : "*.marvel.com",

        apikey : ""

    };
});

