/**
  *MarvelComicsLib
  *
  *This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 07/18/2016
  */


angular.module('MarvelComicsLib').factory('FormatTypeEnum', function() {
    return {

        //TODO: Write general description for this element    
        COLLECTION : "collection",

        //TODO: Write general description for this element    
        COMIC : "comic",
    };
});