/**
  *MarvelComicsLib
  *
  * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 07/18/2016
  */

'use strict';
angular.module('MarvelComicsLib').factory('EventsController',function($q,Configuration,HttpClient,APIHelper){
    return{
        /**
         * Fetches lists of events filtered by a character id.
         * @param {string} characterId    Required parameter: The character ID.
         * @param {string|null} comics    Optional parameter: Return only events which take place in the specified comics (accepts a comma-separated list of ids).
         * @param {string|null} creators    Optional parameter: Return only events which feature work by the specified creators (accepts a comma-separated list of ids).
         * @param {string|null} limit    Optional parameter: Limit the result set to the specified number of resources.
         * @param {string|null} modifiedSince    Optional parameter: Return only events which have been modified since the specified date.
         * @param {string|null} name    Optional parameter: Filter the event list by name.
         * @param {string|null} nameStartsWith    Optional parameter: Return events with names that begin with the specified string (e.g. Sp).
         * @param {string|null} offset    Optional parameter: Skip the specified number of resources in the result set.
         * @param {string|null} orderBy    Optional parameter: Order the result set by a field or fields. Add a "-" to the value sort in descending order. Multiple values are given priority in the order in which they are passed. (Acceptable values are: "name", "startDate", "modified", "-name", "-startDate", "-modified")
         * @param {string|null} series    Optional parameter: Return only events which are part of the specified series (accepts a comma-separated list of ids).
         * @param {string|null} stories    Optional parameter: Return only events which contain the specified stories (accepts a comma-separated list of ids).
         *
         * @return {promise<EventDataWrapper>}
         */
        getCharacterEventsCollection : function(characterId, comics, creators, limit, modifiedSince, name, nameStartsWith, offset, orderBy, series, stories){
            //Assign default values
            orderBy = orderBy || "name";

            //Create promise to return
            var _deffered= $q.defer();
            
            //prepare query string for API call
            var _baseUri = Configuration.BASEURI
            var _queryBuilder = _baseUri + "/v1/public/characters/{characterId}/events";
            
            //Process template parameters
            _queryBuilder = APIHelper.appendUrlWithTemplateParameters(_queryBuilder, {
                "characterId" : characterId
            });

            //Process query parameters
            _queryBuilder = APIHelper.appendUrlWithQueryParameters(_queryBuilder, {
                "comics" : comics,
                "creators" : creators,
                "limit" : limit,
                "modifiedSince" : modifiedSince,
                "name" : name,
                "nameStartsWith" : nameStartsWith,
                "offset" : offset,
                "orderBy" : (null != orderBy)? orderBy: "name",
                "series" : series,
                "stories" : stories,
                "apikey" : Configuration.apikey
            });

            //validate and preprocess url
            var _queryUrl = APIHelper.cleanUrl(_queryBuilder);
            
            //prepare headers
            var _headers = {
                "accept" : "application/json",
                "referer" : Configuration.referer
            };

            //prepare and invoke the API call request to fetch the response
            var _config = {
                method : "GET",
                queryUrl : _queryUrl,
                headers: _headers,
            };
            
            var _response = HttpClient(_config);
            
            //process response
            _response.then(function(_result){
                _deffered.resolve(_result.body);
            },function(_result){
                //Error handling for custom HTTP status codes
                if (_result.code == 409) {
                    _deffered.reject(APIHelper.appendContext({errorMessage: "Limit greater than 100.", errorCode: 409, errorResponse: _result.message},_result.getContext()));
                } else {
                    _deffered.reject(APIHelper.appendContext({errorMessage:"HTTP Response Not OK", errorCode: _result.code, errorResponse: _result.message},_result.getContext()));
                }
            });
            
            return _deffered.promise;
        },
        /**
         * Fetches lists of events filtered by a comic id.
         * @param {string} comicId    Required parameter: The comic ID.
         * @param {string|null} characters    Optional parameter: Return only events which feature the specified characters (accepts a comma-separated list of ids).
         * @param {string|null} creators    Optional parameter: Return only events which feature work by the specified creators (accepts a comma-separated list of ids).
         * @param {string|null} limit    Optional parameter: Limit the result set to the specified number of resources.
         * @param {string|null} modifiedSince    Optional parameter: Return only events which have been modified since the specified date.
         * @param {string|null} name    Optional parameter: Filter the event list by name.
         * @param {string|null} nameStartsWith    Optional parameter: Return events with names that begin with the specified string (e.g. Sp).
         * @param {string|null} offset    Optional parameter: Skip the specified number of resources in the result set.
         * @param {string|null} orderBy    Optional parameter: Order the result set by a field or fields. Add a "-" to the value sort in descending order. Multiple values are given priority in the order in which they are passed. (Acceptable values are: "name", "startDate", "modified", "-name", "-startDate", "-modified")
         * @param {string|null} series    Optional parameter: Return only events which are part of the specified series (accepts a comma-separated list of ids).
         * @param {string|null} stories    Optional parameter: Return only events which contain the specified stories (accepts a comma-separated list of ids).
         *
         * @return {promise<EventDataWrapper>}
         */
        getIssueEventsCollection : function(comicId, characters, creators, limit, modifiedSince, name, nameStartsWith, offset, orderBy, series, stories){
            //Assign default values
            orderBy = orderBy || "name";

            //Create promise to return
            var _deffered= $q.defer();
            
            //prepare query string for API call
            var _baseUri = Configuration.BASEURI
            var _queryBuilder = _baseUri + "/v1/public/comics/{comicId}/events";
            
            //Process template parameters
            _queryBuilder = APIHelper.appendUrlWithTemplateParameters(_queryBuilder, {
                "comicId" : comicId
            });

            //Process query parameters
            _queryBuilder = APIHelper.appendUrlWithQueryParameters(_queryBuilder, {
                "characters" : characters,
                "creators" : creators,
                "limit" : limit,
                "modifiedSince" : modifiedSince,
                "name" : name,
                "nameStartsWith" : nameStartsWith,
                "offset" : offset,
                "orderBy" : (null != orderBy)? orderBy: "name",
                "series" : series,
                "stories" : stories,
                "apikey" : Configuration.apikey
            });

            //validate and preprocess url
            var _queryUrl = APIHelper.cleanUrl(_queryBuilder);
            
            //prepare headers
            var _headers = {
                "accept" : "application/json",
                "referer" : Configuration.referer
            };

            //prepare and invoke the API call request to fetch the response
            var _config = {
                method : "GET",
                queryUrl : _queryUrl,
                headers: _headers,
            };
            
            var _response = HttpClient(_config);
            
            //process response
            _response.then(function(_result){
                _deffered.resolve(_result.body);
            },function(_result){
                //Error handling for custom HTTP status codes
                if (_result.code == 409) {
                    _deffered.reject(APIHelper.appendContext({errorMessage: "Limit greater than 100.", errorCode: 409, errorResponse: _result.message},_result.getContext()));
                } else {
                    _deffered.reject(APIHelper.appendContext({errorMessage:"HTTP Response Not OK", errorCode: _result.code, errorResponse: _result.message},_result.getContext()));
                }
            });
            
            return _deffered.promise;
        },
        /**
         * Fetches lists of events filtered by a creator id.
         * @param {string} creatorId    Required parameter: The creator ID.
         * @param {string|null} characters    Optional parameter: Return only events which feature the specified characters (accepts a comma-separated list of ids).
         * @param {string|null} comics    Optional parameter: Return only events which take place in the specified comics (accepts a comma-separated list of ids).
         * @param {string|null} limit    Optional parameter: Limit the result set to the specified number of resources.
         * @param {string|null} modifiedSince    Optional parameter: Return only events which have been modified since the specified date.
         * @param {string|null} name    Optional parameter: Filter the event list by name.
         * @param {string|null} nameStartsWith    Optional parameter: Return events with names that begin with the specified string (e.g. Sp).
         * @param {string|null} offset    Optional parameter: Skip the specified number of resources in the result set.
         * @param {string|null} orderBy    Optional parameter: Order the result set by a field or fields. Add a "-" to the value sort in descending order. Multiple values are given priority in the order in which they are passed. (Acceptable values are: "name", "startDate", "modified", "-name", "-startDate", "-modified")
         * @param {string|null} series    Optional parameter: Return only events which are part of the specified series (accepts a comma-separated list of ids).
         * @param {string|null} stories    Optional parameter: Return only events which contain the specified stories (accepts a comma-separated list of ids).
         *
         * @return {promise<EventDataWrapper>}
         */
        getCreatorEventsCollection : function(creatorId, characters, comics, limit, modifiedSince, name, nameStartsWith, offset, orderBy, series, stories){
            //Assign default values
            orderBy = orderBy || "name";

            //Create promise to return
            var _deffered= $q.defer();
            
            //prepare query string for API call
            var _baseUri = Configuration.BASEURI
            var _queryBuilder = _baseUri + "/v1/public/creators/{creatorId}/events";
            
            //Process template parameters
            _queryBuilder = APIHelper.appendUrlWithTemplateParameters(_queryBuilder, {
                "creatorId" : creatorId
            });

            //Process query parameters
            _queryBuilder = APIHelper.appendUrlWithQueryParameters(_queryBuilder, {
                "characters" : characters,
                "comics" : comics,
                "limit" : limit,
                "modifiedSince" : modifiedSince,
                "name" : name,
                "nameStartsWith" : nameStartsWith,
                "offset" : offset,
                "orderBy" : (null != orderBy)? orderBy: "name",
                "series" : series,
                "stories" : stories,
                "apikey" : Configuration.apikey
            });

            //validate and preprocess url
            var _queryUrl = APIHelper.cleanUrl(_queryBuilder);
            
            //prepare headers
            var _headers = {
                "accept" : "application/json",
                "referer" : Configuration.referer
            };

            //prepare and invoke the API call request to fetch the response
            var _config = {
                method : "GET",
                queryUrl : _queryUrl,
                headers: _headers,
            };
            
            var _response = HttpClient(_config);
            
            //process response
            _response.then(function(_result){
                _deffered.resolve(_result.body);
            },function(_result){
                //Error handling for custom HTTP status codes
                if (_result.code == 409) {
                    _deffered.reject(APIHelper.appendContext({errorMessage: "Limit greater than 100.", errorCode: 409, errorResponse: _result.message},_result.getContext()));
                } else {
                    _deffered.reject(APIHelper.appendContext({errorMessage:"HTTP Response Not OK", errorCode: _result.code, errorResponse: _result.message},_result.getContext()));
                }
            });
            
            return _deffered.promise;
        },
        /**
         * Fetches lists of events.
         * @param {string|null} characters    Optional parameter: Return only events which feature the specified characters (accepts a comma-separated list of ids).
         * @param {string|null} comics    Optional parameter: Return only events which take place in the specified comics (accepts a comma-separated list of ids).
         * @param {string|null} creators    Optional parameter: Return only events which feature work by the specified creators (accepts a comma-separated list of ids).
         * @param {string|null} limit    Optional parameter: Limit the result set to the specified number of resources.
         * @param {string|null} modifiedSince    Optional parameter: Return only events which have been modified since the specified date.
         * @param {string|null} name    Optional parameter: Return only events which match the specified name.
         * @param {string|null} nameStartsWith    Optional parameter: Return events with names that begin with the specified string (e.g. Sp).
         * @param {string|null} offset    Optional parameter: Skip the specified number of resources in the result set.
         * @param {string|null} orderBy    Optional parameter: Order the result set by a field or fields. Add a "-" to the value sort in descending order. Multiple values are given priority in the order in which they are passed. (Acceptable values are: "name", "startDate", "modified", "-name", "-startDate", "-modified")
         * @param {string|null} series    Optional parameter: Return only events which are part of the specified series (accepts a comma-separated list of ids).
         * @param {string|null} stories    Optional parameter: Return only events which take place in the specified stories (accepts a comma-separated list of ids).
         *
         * @return {promise<EventDataWrapper>}
         */
        getEventsCollection : function(characters, comics, creators, limit, modifiedSince, name, nameStartsWith, offset, orderBy, series, stories){
            //Assign default values
            orderBy = orderBy || "name";

            //Create promise to return
            var _deffered= $q.defer();
            
            //prepare query string for API call
            var _baseUri = Configuration.BASEURI
            var _queryBuilder = _baseUri + "/v1/public/events";
            
            //Process query parameters
            _queryBuilder = APIHelper.appendUrlWithQueryParameters(_queryBuilder, {
                "characters" : characters,
                "comics" : comics,
                "creators" : creators,
                "limit" : limit,
                "modifiedSince" : modifiedSince,
                "name" : name,
                "nameStartsWith" : nameStartsWith,
                "offset" : offset,
                "orderBy" : (null != orderBy)? orderBy: "name",
                "series" : series,
                "stories" : stories,
                "apikey" : Configuration.apikey
            });

            //validate and preprocess url
            var _queryUrl = APIHelper.cleanUrl(_queryBuilder);
            
            //prepare headers
            var _headers = {
                "accept" : "application/json",
                "referer" : Configuration.referer
            };

            //prepare and invoke the API call request to fetch the response
            var _config = {
                method : "GET",
                queryUrl : _queryUrl,
                headers: _headers,
            };
            
            var _response = HttpClient(_config);
            
            //process response
            _response.then(function(_result){
                _deffered.resolve(_result.body);
            },function(_result){
                //Error handling for custom HTTP status codes
                if (_result.code == 409) {
                    _deffered.reject(APIHelper.appendContext({errorMessage: "Limit greater than 100.", errorCode: 409, errorResponse: _result.message},_result.getContext()));
                } else {
                    _deffered.reject(APIHelper.appendContext({errorMessage:"HTTP Response Not OK", errorCode: _result.code, errorResponse: _result.message},_result.getContext()));
                }
            });
            
            return _deffered.promise;
        },
        /**
         * Fetches a single event by id.
         * @param {string} eventId    Required parameter: A single event.
         *
         * @return {promise<Event>}
         */
        getEventIndividual : function(eventId){

            //Create promise to return
            var _deffered= $q.defer();
            
            //prepare query string for API call
            var _baseUri = Configuration.BASEURI
            var _queryBuilder = _baseUri + "/v1/public/events/{eventId}";
            
            //Process template parameters
            _queryBuilder = APIHelper.appendUrlWithTemplateParameters(_queryBuilder, {
                "eventId" : eventId
            });

            //Process query parameters
            _queryBuilder = APIHelper.appendUrlWithQueryParameters(_queryBuilder, {
                "apikey" : Configuration.apikey
            });

            //validate and preprocess url
            var _queryUrl = APIHelper.cleanUrl(_queryBuilder);
            
            //prepare headers
            var _headers = {
                "accept" : "application/json",
                "referer" : Configuration.referer
            };

            //prepare and invoke the API call request to fetch the response
            var _config = {
                method : "GET",
                queryUrl : _queryUrl,
                headers: _headers,
            };
            
            var _response = HttpClient(_config);
            
            //process response
            _response.then(function(_result){
                _deffered.resolve(_result.body);
            },function(_result){
                //Error handling for custom HTTP status codes
                if (_result.code == 404) {
                    _deffered.reject(APIHelper.appendContext({errorMessage: "Event not found.", errorCode: 404, errorResponse: _result.message},_result.getContext()));
                } else {
                    _deffered.reject(APIHelper.appendContext({errorMessage:"HTTP Response Not OK", errorCode: _result.code, errorResponse: _result.message},_result.getContext()));
                }
            });
            
            return _deffered.promise;
        },
        /**
         * Fetches lists of events filtered by a series id.
         * @param {string} seriesId    Required parameter: The series ID.
         * @param {string|null} characters    Optional parameter: Return only events which feature the specified characters (accepts a comma-separated list of ids).
         * @param {string|null} comics    Optional parameter: Return only events which take place in the specified comics (accepts a comma-separated list of ids).
         * @param {string|null} creators    Optional parameter: Return only events which feature work by the specified creators (accepts a comma-separated list of ids).
         * @param {string|null} limit    Optional parameter: Limit the result set to the specified number of resources.
         * @param {string|null} modifiedSince    Optional parameter: Return only events which have been modified since the specified date.
         * @param {string|null} name    Optional parameter: Filter the event list by name.
         * @param {string|null} nameStartsWith    Optional parameter: Return events with names that begin with the specified string (e.g. Sp).
         * @param {string|null} offset    Optional parameter: Skip the specified number of resources in the result set.
         * @param {string|null} orderBy    Optional parameter: Order the result set by a field or fields. Add a "-" to the value sort in descending order. Multiple values are given priority in the order in which they are passed. (Acceptable values are: "name", "startDate", "modified", "-name", "-startDate", "-modified")
         * @param {string|null} stories    Optional parameter: Return only events which contain the specified stories (accepts a comma-separated list of ids).
         *
         * @return {promise<EventDataWrapper>}
         */
        getEventsCollectionBySeriesId : function(seriesId, characters, comics, creators, limit, modifiedSince, name, nameStartsWith, offset, orderBy, stories){
            //Assign default values
            orderBy = orderBy || "name";

            //Create promise to return
            var _deffered= $q.defer();
            
            //prepare query string for API call
            var _baseUri = Configuration.BASEURI
            var _queryBuilder = _baseUri + "/v1/public/series/{seriesId}/events";
            
            //Process template parameters
            _queryBuilder = APIHelper.appendUrlWithTemplateParameters(_queryBuilder, {
                "seriesId" : seriesId
            });

            //Process query parameters
            _queryBuilder = APIHelper.appendUrlWithQueryParameters(_queryBuilder, {
                "characters" : characters,
                "comics" : comics,
                "creators" : creators,
                "limit" : limit,
                "modifiedSince" : modifiedSince,
                "name" : name,
                "nameStartsWith" : nameStartsWith,
                "offset" : offset,
                "orderBy" : (null != orderBy)? orderBy: "name",
                "stories" : stories,
                "apikey" : Configuration.apikey
            });

            //validate and preprocess url
            var _queryUrl = APIHelper.cleanUrl(_queryBuilder);
            
            //prepare headers
            var _headers = {
                "accept" : "application/json",
                "referer" : Configuration.referer
            };

            //prepare and invoke the API call request to fetch the response
            var _config = {
                method : "GET",
                queryUrl : _queryUrl,
                headers: _headers,
            };
            
            var _response = HttpClient(_config);
            
            //process response
            _response.then(function(_result){
                _deffered.resolve(_result.body);
            },function(_result){
                //Error handling for custom HTTP status codes
                if (_result.code == 409) {
                    _deffered.reject(APIHelper.appendContext({errorMessage: "Limit greater than 100.", errorCode: 409, errorResponse: _result.message},_result.getContext()));
                } else {
                    _deffered.reject(APIHelper.appendContext({errorMessage:"HTTP Response Not OK", errorCode: _result.code, errorResponse: _result.message},_result.getContext()));
                }
            });
            
            return _deffered.promise;
        },
        /**
         * Fetches lists of events filtered by a story id.
         * @param {string} storyId    Required parameter: The story ID.
         * @param {string|null} characters    Optional parameter: Return only events which feature the specified characters (accepts a comma-separated list of ids).
         * @param {string|null} comics    Optional parameter: Return only events which take place in the specified comics (accepts a comma-separated list of ids).
         * @param {string|null} creators    Optional parameter: Return only events which feature work by the specified creators (accepts a comma-separated list of ids).
         * @param {string|null} limit    Optional parameter: Limit the result set to the specified number of resources.
         * @param {string|null} modifiedSince    Optional parameter: Return only events which have been modified since the specified date.
         * @param {string|null} name    Optional parameter: Filter the event list by name.
         * @param {string|null} nameStartsWith    Optional parameter: Return events with names that begin with the specified string (e.g. Sp).
         * @param {string|null} offset    Optional parameter: Skip the specified number of resources in the result set.
         * @param {string|null} orderBy    Optional parameter: Order the result set by a field or fields. Add a "-" to the value sort in descending order. Multiple values are given priority in the order in which they are passed. (Acceptable values are: "name", "startDate", "modified", "-name", "-startDate", "-modified")
         * @param {string|null} series    Optional parameter: Return only events which are part of the specified series (accepts a comma-separated list of ids).
         *
         * @return {promise<EventDataWrapper>}
         */
        getEventsCollectionByStoryId : function(storyId, characters, comics, creators, limit, modifiedSince, name, nameStartsWith, offset, orderBy, series){
            //Assign default values
            orderBy = orderBy || "name";

            //Create promise to return
            var _deffered= $q.defer();
            
            //prepare query string for API call
            var _baseUri = Configuration.BASEURI
            var _queryBuilder = _baseUri + "/v1/public/stories/{storyId}/events";
            
            //Process template parameters
            _queryBuilder = APIHelper.appendUrlWithTemplateParameters(_queryBuilder, {
                "storyId" : storyId
            });

            //Process query parameters
            _queryBuilder = APIHelper.appendUrlWithQueryParameters(_queryBuilder, {
                "characters" : characters,
                "comics" : comics,
                "creators" : creators,
                "limit" : limit,
                "modifiedSince" : modifiedSince,
                "name" : name,
                "nameStartsWith" : nameStartsWith,
                "offset" : offset,
                "orderBy" : (null != orderBy)? orderBy: "name",
                "series" : series,
                "apikey" : Configuration.apikey
            });

            //validate and preprocess url
            var _queryUrl = APIHelper.cleanUrl(_queryBuilder);
            
            //prepare headers
            var _headers = {
                "accept" : "application/json",
                "referer" : Configuration.referer
            };

            //prepare and invoke the API call request to fetch the response
            var _config = {
                method : "GET",
                queryUrl : _queryUrl,
                headers: _headers,
            };
            
            var _response = HttpClient(_config);
            
            //process response
            _response.then(function(_result){
                _deffered.resolve(_result.body);
            },function(_result){
                //Error handling for custom HTTP status codes
                if (_result.code == 409) {
                    _deffered.reject(APIHelper.appendContext({errorMessage: "Limit greater than 100.", errorCode: 409, errorResponse: _result.message},_result.getContext()));
                } else {
                    _deffered.reject(APIHelper.appendContext({errorMessage:"HTTP Response Not OK", errorCode: _result.code, errorResponse: _result.message},_result.getContext()));
                }
            });
            
            return _deffered.promise;
        }
    }
});